import {
  FaReact,
  FaNodeJs,
  FaBootstrap,
  FaPython,
  FaGithub,
  FaLinkedin,
  FaCoffee,
  FaGitAlt,
  FaLinux,
  FaFigma,
  FaHtml5,
  FaCss3,
  FaDev,
  FaEnvelope,
  FaVuejs,
  FaFilePdf,
  FaJava,
} from "react-icons/fa";
import {
  SiTailwindcss,
  SiExpress,
  SiMongodb,
  SiRedux,
  SiSupabase,
  SiNextdotjs,
  SiAstro,
  SiTrpc,
  SiPostgresql,
  SiDrizzle,
  SiDocker,
  SiSpring,
  SiSocketdotio,
} from "react-icons/si";
import { IoLogoJavascript } from "react-icons/io";
import { TbBrandTypescript } from "react-icons/tb";

export const skillIcons = [
  FaPython,
  FaGitAlt,
  SiDocker,
  FaLinux,
  FaFigma,
  FaHtml5,
  FaCss3,
  SiTailwindcss,
  FaBootstrap,
  IoLogoJavascript,
  TbBrandTypescript,
  FaReact,
  SiRedux,
  SiNextdotjs,
  FaVuejs,
  SiAstro,
  FaNodeJs,
  SiExpress,
  SiTrpc,
  SiMongodb,
  SiPostgresql,
  SiDrizzle,
  SiSupabase,
  FaJava,
  SiSpring,
  SiSocketdotio,
];

export const socialLinkSet = {
  "https://raw.githubusercontent.com/NureddinFarzaliyev/resume/master/Nureddin_Farzaliyev_CV.pdf":
    FaFilePdf,
  "https://www.github.com/nureddinfarzaliyev": FaGithub,
  "https://www.linkedin.com/in/nureddinfarzaliyev": FaLinkedin,
  "https://dev.to/nureddinfarzaliyev": FaDev,
  "frzlyv@proton.me": FaEnvelope,
  "https://www.kofe.al/farzaliyev": FaCoffee,
};
